In [2]:
import numpy as np
nums=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[2,3,4,5],[4,5,6,7]])
nums[:,0] # 和MATLAB不同的是 矩阵的index是从0开始

array([1, 5, 9, 2, 4])

In [13]:
nums[:,2]

array([ 3,  7, 11,  4,  6])

In [26]:
nums[1:4,1:4] #并不包括矩阵中的第4行和列  只取1,2,3行和1,2,3列的数

array([[ 6,  7,  8],
       [10, 11, 12],
       [ 3,  4,  5]])

In [31]:
nums[:,0:-1] #取所有行，第1列到最后1列的前一列的所有数 -1代表最后1列，相当于从后面数起

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 2,  3,  4],
       [ 4,  5,  6]])

In [30]:
nums[:,[-1]] # -1 加大括号保持原来形式输出

array([[ 4],
       [ 8],
       [12],
       [ 5],
       [ 7]])

In [3]:
import tensorflow as tf
xy = np.loadtxt('dataset-test.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, "\n",x_data, "\n",len(x_data))
print(y_data.shape,  "\n",y_data)
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

(25, 3) 
 [[  77.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 
 25
(25, 1) 
 [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]
0 Cost:  61282.1 
Prediction:
 [[ -78.21605682]
 [ -94.77337646]
 [ -92.38766479]
 [-101.59868622]
 [ -72.00102234]
 [ -55.02175903]
 [ -77.21743774]
 [ -58.77343369]
 [ -90.27877045]
 [ -86.09499359]
 [ -73.88796997]
 [ -7

In [1]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  13194.9 
Prediction:
 [[ 39.55213165]
 [ 50.90582657]
 [ 48.31090927]
 [ 53.44791794]
 [ 39.06949615]
 [ 30.67482758]
 [ 40.4495163 ]
 [ 30.46049881]
 [ 49.47437286]
 [ 48.09904861]]
10 Cost:  5.39557 
Prediction:
 [[ 151.56341553]
 [ 185.54740906]
 [ 180.96760559]
 [ 197.92649841]
 [ 141.75476074]
 [ 106.39044952]
 [ 148.60075378]
 [ 110.64237976]
 [ 175.31639099]
 [ 164.67253113]]
20 Cost:  6.71776 
Prediction:
 [[ 152.32225037]
 [ 186.45227051]
 [ 181.86282349]
 [ 198.90242004]
 [ 142.44229126]
 [ 106.89801788]
 [ 149.3347168 ]
 [ 111.19153595]
 [ 176.16160583]
 [ 165.45689392]]
30 Cost:  6.71854 
Prediction:
 [[ 152.33030701]
 [ 186.45469666]
 [ 181.86886597]
 [ 198.90995789]
 [ 142.44154358]
 [ 106.8980484 ]
 [ 149.34379578]
 [ 111.20330048]
 [ 176.16331482]
 [ 165.4598999 ]]
40 Cost:  6.70636 
Prediction:
 [[ 152.33331299]
 [ 186.45101929]
 [ 181.868927  ]
 [ 198.91094971]
 [ 142.43615723]
 [ 106.89466095]
 [ 149.34797668]
 [ 111.21141052]
 [ 176.15933228]
 [ 165.4576416