In [20]:
# Lab 6 Softmax Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))   #去掉第二维（列），把所有列加到1列，变为8行1列

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost,feed_dict={X: x_data, Y: y_data}),"\n",sess.run(W),"\n",sess.run(b))

0 4.00515 
 [[-0.09576704  0.61926496 -0.64923644]
 [ 1.5735693   0.92762113 -0.84375721]
 [ 0.73249066  0.84330904 -0.81611741]
 [-0.47443712 -0.35836929 -0.97443074]] 
 [ 0.55744743  1.51085937  2.12309408]
200 0.518915 
 [[-1.20510519  0.12391334  0.95545399]
 [ 0.63723081  0.41628206  0.60392094]
 [ 0.95099103  0.29353434 -0.48484296]
 [-0.76693422 -0.14341538 -0.89688635]] 
 [-0.21757105  0.81603706  3.59293461]
400 0.427704 
 [[-1.73363912  0.23079357  1.37710714]
 [ 0.5005883   0.42755333  0.72929198]
 [ 1.46668541  0.12487977 -0.83188319]
 [-0.9103421   0.06696576 -0.96385932]] 
 [-0.66392386  0.65892124  4.1964035 ]
600 0.354023 
 [[-2.14886212  0.33604822  1.6870755 ]
 [ 0.40230229  0.44780451  0.80732697]
 [ 1.93161678 -0.02114696 -1.15078735]
 [-1.07973588  0.21392256 -0.94142115]] 
 [-1.04441404  0.56493348  4.67088079]
800 0.281645 
 [[-2.48695421  0.41979462  1.94142175]
 [ 0.32836595  0.46133542  0.86773235]
 [ 2.34419036 -0.14655599 -1.43795049]
 [-1.23478639  0.323817

In [109]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
W=[[-0.09576704  ,0.61926496 ,-0.64923644],
 [1.5735693  , 0.92762113, -0.84375721],
 [ 0.73249066 , 0.84330904, -0.81611741],
 [-0.47443712, -0.35836929 ,-0.97443074]]
b= [ 0.55744743 , 1.51085937 , 2.12309408]
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
sess=tf.Session()
print(sess.run(hypothesis,feed_dict={X: x_data, Y: y_data}))
print("\n",sess.run(tf.log(hypothesis),feed_dict={X: x_data, Y: y_data}))
print("\n",sess.run(Y*tf.log(hypothesis),feed_dict={X: x_data, Y: y_data}))
print("\n",sess.run(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1),feed_dict={X: x_data, Y: y_data}))
print("\n",sess.run(tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)),feed_dict={X: x_data, Y: y_data}))

[[  3.53206366e-01   6.45797729e-01   9.95982904e-04]
 [  9.09435377e-02   9.09011185e-01   4.53116045e-05]
 [  3.73523980e-02   9.62643683e-01   3.93639539e-06]
 [  1.33602265e-02   9.86639798e-01   2.21808101e-08]
 [  8.47969353e-01   1.52030647e-01   3.72100441e-12]
 [  1.64235279e-01   8.35764647e-01   7.75817171e-08]
 [  6.99712157e-01   3.00287932e-01   4.43950519e-12]
 [  7.79883862e-01   2.20116094e-01   5.68743932e-14]]

 [[ -1.04070282e+00  -4.37268943e-01  -6.91178036e+00]
 [ -2.39751649e+00  -9.53978822e-02  -1.00019474e+01]
 [ -3.28735828e+00  -3.80719416e-02  -1.24452448e+01]
 [ -4.31547308e+00  -1.34502528e-02  -1.76240387e+01]
 [ -1.64910778e-01  -1.88367319e+00  -2.63170280e+01]
 [ -1.80645525e+00  -1.79408222e-01  -1.63719349e+01]
 [ -3.57086241e-01  -1.20301354e+00  -2.61404781e+01]
 [ -2.48610273e-01  -1.51360011e+00  -3.04979305e+01]]

 [[ -0.          -0.          -6.91178036]
 [ -0.          -0.         -10.0019474 ]
 [ -0.          -0.         -12.44524479]
 [ -

In [57]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 200 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val,sess.run(w1),sess.run(w2),sess.run(w3),sess.run(b))

Tensor("add_42:0", dtype=float32)
0 Cost:  22662.1 
Prediction:
 [ 14.63983059  26.5960598   21.79611778  21.39977074  24.36887169] [ 1.70463467] [-0.16827568] [-0.4957386] [-0.37660936]
200 Cost:  8.65489 
Prediction:
 [ 148.40167236  186.95878601  180.01626587  193.68281555  146.59565735] [ 2.003546] [ 0.18925953] [-0.16831425] [-0.37333924]
400 Cost:  7.86716 
Prediction:
 [ 148.60627747  186.81759644  180.07780457  193.73632812  146.40278625] [ 1.97704542] [ 0.21865304] [-0.17113899] [-0.3738575]
600 Cost:  7.15948 
Prediction:
 [ 148.7999115   186.68395996  180.13598633  193.78739929  146.21983337] [ 1.95183623] [ 0.24644259] [-0.17365664] [-0.37436461]
800 Cost:  6.52373 
Prediction:
 [ 148.98312378  186.55744934  180.19096375  193.83609009  146.04629517] [ 1.92785156] [ 0.27271301] [-0.17588431] [-0.37486112]
1000 Cost:  5.95253 
Prediction:
 [ 149.15646362  186.43768311  180.24290466  193.88253784  145.88166809] [ 1.90502608] [ 0.29754496] [-0.17783774] [-0.37534705]
1200 Cost:

In [63]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)
w1=[ 1.80628181]
w2=[ 0.40265432]
w3=[-0.18399982]
b=[-0.37763792]
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

sess = tf.Session()
print(sess.run(tf.square(hypothesis - Y),feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data}))
print(sess.run(tf.reduce_mean(tf.square(hypothesis - Y)),feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data}))

[  4.43826914   0.86148399   0.21436663   3.66509581  10.08771896]
3.85339


In [107]:
x=[ [73., 93., 89., 96., 73.], [80., 88., 91., 98., 66.],[75., 93., 90., 100., 70.]]
x=tf.transpose(x,perm=[1,0])
W=[[ 1.80628181,1],
   [ 0.40265432,2],
   [-0.18399982,3]]
b=[-0.37763792]
y=tf.matmul(x,W)+b
p=[[0.,0.,1.,1.,0.],[1.,1.,0.,1.,1.]]
sess = tf.Session()
print(sess.run(tf.matmul(y,p)))

[[ 457.62237549  457.62237549  149.89328003  607.515625    457.62237549]
 [ 547.62237549  547.62237549  185.92816162  733.55053711  547.62237549]
 [ 540.62237549  540.62237549  180.46299744  721.08538818  540.62237549]
 [ 591.62237549  591.62237549  194.08555603  785.70794678  591.62237549]
 [ 414.62237549  414.62237549  145.17611694  559.79846191  414.62237549]]


In [111]:
x=[ [73., 93., 89., 96., 73.], [80., 88., 91., 98., 66.],[75., 93., 90., 100., 70.]]
y=tf.reduce_sum(x,axis=0)
sess = tf.Session()
print(sess.run(y))

[ 228.  274.  270.  294.  209.]
