In [7]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) # 1行有三个值，none在这个例子可填5，也可填none自动获取
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight') #产生3行1列的W值
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b # matmul表示矩阵相乘

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  107669.0 
Prediction:
 [[-138.7796936 ]
 [-166.25592041]
 [-164.41891479]
 [-175.729599  ]
 [-129.30340576]]
10 Cost:  8.03335 
Prediction:
 [[ 151.47351074]
 [ 182.61903381]
 [ 179.32722473]
 [ 198.60107422]
 [ 136.80361938]]
20 Cost:  7.02905 
Prediction:
 [[ 152.34529114]
 [ 183.67912292]
 [ 180.36546326]
 [ 199.73143005]
 [ 137.61546326]]
30 Cost:  7.01041 
Prediction:
 [[ 152.34152222]
 [ 183.68681335]
 [ 180.36672974]
 [ 199.73258972]
 [ 137.62458801]]
40 Cost:  6.99186 
Prediction:
 [[ 152.33509827]
 [ 183.69129944]
 [ 180.36488342]
 [ 199.73031616]
 [ 137.6312561 ]]
50 Cost:  6.97341 
Prediction:
 [[ 152.32873535]
 [ 183.69580078]
 [ 180.36308289]
 [ 199.72808838]
 [ 137.63793945]]
60 Cost:  6.9551 
Prediction:
 [[ 152.32234192]
 [ 183.70025635]
 [ 180.36123657]
 [ 199.72583008]
 [ 137.64454651]]
70 Cost:  6.93679 
Prediction:
 [[ 152.31599426]
 [ 183.70471191]
 [ 180.35939026]
 [ 199.72357178]
 [ 137.65118408]]
80 Cost:  6.91863 
Prediction:
 [[ 152.30963135]
 [ 183.7

In [6]:
# matmul 用法
matrix1 = tf.constant([[70., 80,75,90],[93,88,93,90],[89,91,90,90]])
matrix2 = tf.constant([[2.],[2.],[2],[2]]) 

product = tf.matmul(matrix1, matrix2)
sess=tf.Session()
print(sess.run(product))


[[ 630.]
 [ 728.]
 [ 720.]]
