In [25]:
import tensorflow as tf
import numpy as np
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-2)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 Cost:  1.38135 
Prediction:
 [[ 2.66414547]
 [ 2.28336263]
 [ 1.87669635]
 [ 1.37044692]
 [ 1.75313222]
 [ 1.61373901]
 [ 0.88417935]
 [ 0.58147138]]
1 Cost:  1.27844 
Prediction:
 [[ 2.60419846]
 [ 2.2256422 ]
 [ 1.82850647]
 [ 1.33301902]
 [ 1.70884728]
 [ 1.57097864]
 [ 0.85556722]
 [ 0.55349571]]
2 Cost:  1.18325 
Prediction:
 [[ 2.54652715]
 [ 2.17013264]
 [ 1.782161  ]
 [ 1.29702258]
 [ 1.666255  ]
 [ 1.52985406]
 [ 0.82805711]
 [ 0.52660424]]
3 Cost:  1.0952 
Prediction:
 [[ 2.4910

In [24]:
from sklearn import preprocessing 
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
min_max_scaler = preprocessing.MinMaxScaler()  
xy = min_max_scaler.fit_transform(xy)  
print(xy)
x_data = xy[:, 0:-1]
y_data=  xy[:,[-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-2)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[ 1.          1.          0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881783  0.83755792]
 [ 0.54412549  0.50274824  0.57608696  0.60646801  0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.4258239   0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.4258239   0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 Cost:  0.394819 
Prediction:
 [[-0.36329031]
 [ 0.11710224]
 [ 0.14762697]
 [ 0.17328259]
 [ 0.11389577]
 [ 0.04636541]
 [ 0.36228502]
 [ 0.34607351]]
1 Cost:  0.375844 
Prediction:
 [[-0.3360883 ]
 [ 0.14130546]
 [ 0.16764234]
 [ 0.18855964]
 [ 0.13237207]
 [ 0.06405501]
 [ 0.37279132]
 [ 0.35571498]]
2 Cost:  0.358223 
Prediction:
 [[-0.30984509]
 [ 0.1645847 ]
 [ 0.186887  ]
 [ 0.20323911]
 [ 0.15014064]
 [ 0.08106129]
 [ 0.38284141]
 [ 0.36490995]]
3 Cost:  0.341857 
Prediction:
 [[-0