In [49]:
#假设有N个2*2的矩阵，axis是对输出的某一个维度进行添加N，这里axis=2即对3维度中的列进行添加，输出结果（2,2,3）如果axis=0，即（N，2,2）
#规律：axis=0时，按原来每个Tensor自己的顺序排列，如x=【【1,2】，【3,4】】重新拼接后仍是它自己
#axis=1时，拼接后第一个矩阵是每个矩阵的第一行按顺序组成新矩阵,第二个矩阵是每个矩阵的第二行按顺序组成的矩阵......
#axis=2时，拼接后第一个矩阵是每个矩阵的第一行转置后按顺序组成的新矩阵，第二个矩阵是每个矩阵的第二行转置后按顺序组成的新矩阵
import tensorflow as tf
x=tf.constant([[1,2],[3,4]])
y=[[5,6],[7,8]]
z=[[9,10],[11,12]]
sess=tf.Session()
print(x)
print('axis=0:',sess.run(tf.stack([x,y,z],axis=0)) )
print('axis=1:',sess.run(tf.stack([x,y,z],axis=1)) )
print('axis=2:',sess.run(tf.stack([x,y,z],axis=2)) )

Tensor("Const_16:0", shape=(2, 2), dtype=int32)
axis=0: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
axis=1: [[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]
axis=2: [[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]
