# 第二次课作业

In [1]:
import numpy as np

（1）创建一个1到10的数组，然后逆序输出。

In [5]:
a = np.arange(1,11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [11]:
b = np.ones(20,dtype=int)
print(b.reshape(4,5))
c.T

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [17]:
print(np.random.rand(3,3,3))
np.random.random((3,3,3))

[[[0.13198316 0.26575247 0.91371687]
  [0.65620095 0.49640354 0.99345886]
  [0.14531347 0.01199521 0.46526874]]

 [[0.18870344 0.16371775 0.00130611]
  [0.6136041  0.48377735 0.62093144]
  [0.91563574 0.47482736 0.34933788]]

 [[0.98143514 0.69736936 0.43740626]
  [0.32325646 0.2249021  0.14690108]
  [0.07643093 0.79318905 0.59034315]]]


array([[[0.00841185, 0.40508194, 0.26735782],
        [0.76322745, 0.05864653, 0.31229276],
        [0.36473653, 0.67983236, 0.33354446]],

       [[0.42586096, 0.51699713, 0.37388498],
        [0.22928778, 0.93862416, 0.37356083],
        [0.37396701, 0.2571255 , 0.22829443]],

       [[0.1862598 , 0.18744221, 0.52250024],
        [0.2939017 , 0.69643526, 0.33484491],
        [0.74043058, 0.20915615, 0.52284892]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [36]:
c = np.random.uniform(1,10,10)
print('排序:',np.sort(c))
print('最大值:',max(c))
print('最小值:',min(c))
print('求和:',sum(c))
print('平方差:',np.var(c))

排序: [1.24730061 2.67625234 3.63087981 5.67256069 6.6911118  7.05178857
 7.25686986 8.67308295 9.0890949  9.1075211 ]
最大值: 9.107521097999252
最小值: 1.2473006062788015
求和: 61.09646262975387
平方差: 6.874335770202173


（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [77]:
c = np.random.randint(1,10,size=10)
print(c)
c = c[c%2==1]
print('奇数:',c)

[3 8 5 8 6 9 5 9 2 1]
奇数: [3 5 9 5 9 1]


（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [48]:
np.linspace(0,100,20,dtype=int)

array([  0,   5,  10,  15,  21,  26,  31,  36,  42,  47,  52,  57,  63,
        68,  73,  78,  84,  89,  94, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [98]:
d = np.random.randint(1,10,size=10)
print(d)
d[(d>3)&(d<8)]*=-1
print(d)

[7 9 6 8 6 6 5 9 8 2]
[-7  9 -6  8 -6 -6 -5  9  8  2]


（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [115]:
e = np.array([1, 2, 3, 4, 5])
e1 = np.zeros(9)
e1[::2] = e
print(e1)

e0 = 1
e1 = np.zeros(len(e)+(len(e)-1)*e0)
e1[::2] = e
print(e1)

[1. 0. 2. 0. 3. 0. 4. 0. 5.]
[1. 0. 2. 0. 3. 0. 4. 0. 5.]


（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [125]:
d = np.random.randint(10,100,size=(5,5))
print(d)
tmp = np.copy(d[0])
d[0] = d[1]
d[1] = tmp
d

[[63 27 38 65 26]
 [27 77 29 72 29]
 [22 88 80 36 89]
 [83 87 50 31 53]
 [76 42 81 12 80]]


array([[27, 77, 29, 72, 29],
       [63, 27, 38, 65, 26],
       [22, 88, 80, 36, 89],
       [83, 87, 50, 31, 53],
       [76, 42, 81, 12, 80]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

In [135]:
Z = np.random.random((10, 2))
print(Z)
x,y = Z[:,0],Z[:,1]
r = np.sqrt(x**2+y**2)
cita = np.arctan2(y,x)
print(r,"\n",cita)

[[0.77086573 0.48129953]
 [0.88268669 0.87901735]
 [0.15137411 0.13117552]
 [0.0685051  0.8789686 ]
 [0.90394967 0.66559156]
 [0.75305892 0.43478946]
 [0.43446389 0.06339448]
 [0.10764376 0.29821808]
 [0.21991525 0.09395826]
 [0.02946069 0.77801685]]
[0.90878117 1.24571557 0.20030262 0.88163413 1.1225583  0.86956289
 0.43906461 0.31705079 0.23914614 0.77857443] 
 [0.55814064 0.78331533 0.71403269 1.49301551 0.63468492 0.52360942
 0.14489174 1.22439424 0.40377283 1.53294802]


（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [144]:
Z = np.ones(10,dtype=int)*2
Z[4] = 1
Z

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

（12）创建一个长度为10的随机向量，并求其累计和。

In [147]:
Z = np.random.random(10)
print(Z)
Z.cumsum()

[0.93583569 0.11975138 0.49565942 0.88743546 0.88112572 0.2266102
 0.53249756 0.09489245 0.68630279 0.20214859]


array([0.93583569, 1.05558707, 1.55124649, 2.43868195, 3.31980767,
       3.54641787, 4.07891543, 4.17380788, 4.86011067, 5.06225926])

（13）将数组中的所有奇数替换成-1。

In [154]:
d = np.random.randint(1,20,size=20)
print(d)
d[d%2==1]=-1
d

[ 4 15  5  7 16  4  1  7  6  8 10  5  2 14 15  6  9  5  1 14]


array([ 4, -1, -1, -1, 16,  4, -1, -1,  6,  8, 10, -1,  2, 14, -1,  6, -1,
       -1, -1, 14])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [164]:
A = np.random.randint(10,100,size=(4,3))
print(A)
B = np.random.randint(10,100,size=(4,3))
print(B)
np.vstack((A,B))

[[61 52 14]
 [67 18 23]
 [40 66 70]
 [36 57 97]]
[[79 28 13]
 [16 52 54]
 [38 58 78]
 [39 37 63]]


array([[61, 52, 14],
       [67, 18, 23],
       [40, 66, 70],
       [36, 57, 97],
       [79, 28, 13],
       [16, 52, 54],
       [38, 58, 78],
       [39, 37, 63]])

In [167]:
print(np.hstack((A,B)))
np.dstack((A,B))

[[61 52 14 79 28 13]
 [67 18 23 16 52 54]
 [40 66 70 38 58 78]
 [36 57 97 39 37 63]]


array([[[61, 79],
        [52, 28],
        [14, 13]],

       [[67, 16],
        [18, 52],
        [23, 54]],

       [[40, 38],
        [66, 58],
        [70, 78]],

       [[36, 39],
        [57, 37],
        [97, 63]]])

（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [187]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a-b
a[np.where(c==0)]

array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [181]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
a[(a>5)&(a<10)]

array([7, 7, 9, 9, 8])